services:
  postgres:
    image: postgres:16
    container_name: tikitaka-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tikitaka
      POSTGRES_USER: tikitaka
      POSTGRES_PASSWORD: tikitaka
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
