name: Backend Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build Spring Boot app
        run: ./gradlew clean build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          echo "Image URI: $IMAGE_URI"

          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

          echo "image=$IMAGE_URI" >> $GITHUB_OUTPUT

      - name: Deploy to ECS Express
        uses: aws-actions/amazon-ecs-deploy-express-service@v1
        with:
          service-name: ${{ secrets.ECS_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          image: ${{ steps.build-image.outputs.image }}
          execution-role-arn: arn:aws:iam::816975652595:role/ecsTaskExecutionRole
          infrastructure-role-arn: arn:aws:iam::816975652595:role/ecsInfrastructureRoleForExpressServices
          container-port: 8080
          health-check-path: /health

      - name: Notify Discord deploy success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
            -d "{
              \"content\": \"✅[BACKEND] 배포 성공\nRepository: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nECS Service: ${{ secrets.ECS_SERVICE }}\nImage: ${{ steps.build-image.outputs.image }}\"
            }" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify Discord deploy failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
            -d "{
              \"content\": \"❌[BACKEND] 배포 실패\nRepository: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nActions / ECS 로그 확인 필요\"
            }" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}